{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ifconfig.fullname" . }}-geoip
  labels:
    {{- include "ifconfig.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geoipupdate.accountId | toString | b64enc | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geoipupdate.licenseKey | toString | b64enc | quote }}
{{- end }}
