{{- if .Values.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ripe-atlas-probe.fullname" . }}-spool
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ripe-atlas-probe.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
