---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install  # This hook ensures the PVC is created before the deployment
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}