apiVersion: v2
name: ripe-atlas-probe
type: application
version: "0.2.0"
appVersion: "1.16.0"
description: A Helm chart to deploy a RIPE NCC software Atlas probe with automatic SSH key generation
home: https://atlas.ripe.net
sources:
  - https://github.com/besmirzanaj/charts
keywords:
  - ripe
  - atlas
  - probe
  - network-monitoring
maintainers:
  - name: Besmir Zanaj
