apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validate-email.fullname" . }}
  labels:
    {{- include "validate-email.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "validate-email.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validate-email.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: VALIDATE_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret | default (include "validate-email.fullname" .) }}
                  key: api_keys
            - name: VALIDATE_SMTP_SENDER
              value: {{ .Values.smtpSender | quote }}
            - name: VALIDATE_SMTP_TIMEOUT
              value: {{ .Values.smtpTimeout | quote }}
            - name: VALIDATE_WAITRESS_THREADS
              value: {{ .Values.waitressThreads | quote }}
            {{- if .Values.cache.enabled }}
            - name: VALIDATE_CACHE_REDIS_URL
              value: "redis://{{ include "validate-email.fullname" . }}-cache-0.{{ include "validate-email.fullname" . }}-cache:6379/0"
            {{- if eq .Values.cache.mode "cluster" }}
            - name: VALIDATE_CACHE_CLUSTER
              value: "true"
            {{- end }}
            {{- end }}
            - name: VALIDATE_CACHE_TTL
              value: {{ .Values.cacheTTL | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
