apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-validate-email
  labels:
    {{- include "validate-email.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.credentials }}
  validate_jwt_key: {{ .validate_jwt_key | default (randAlphaNum 61) | b64enc }}
  validate_api_user: {{ .validate_api_user | default "validate" | b64enc }}
  validate_api_password: {{ .validate_api_password | default (randAlphaNum 25) | b64enc }}
  {{- end }}