{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validate-email.fullname" . }}
  labels:
    {{- include "validate-email.labels" . | nindent 4 }}
type: Opaque
data:
  api_keys: {{ (.Values.apiKeys | default (randAlphaNum 32)) | b64enc }}
{{- end }}
