apiVersion: v2
name: ifconfig
type: application
version: "0.1.0"
appVersion: "1.0.0"
description: A Helm chart to deploy echoip with GeoIP databases (GeoLite2)
home: https://github.com/besmirzanaj/echoip
sources:
  - https://github.com/besmirzanaj/charts
keywords:
  - ifconfig
  - echoip
  - geoip
  - ip-lookup
maintainers:
  - name: Besmir Zanaj
